<?php
/*
$mail->isSMTP();
$mail->Host = 'pop.secureserver.net';
$mail->SMTPAuth = true;
$mail->Username = 'contact@abc.com'; //paste one generated by Mailtrap
$mail->Password = 'i]abc'; //paste one generated by Mailtrap
$mail->SMTPSecure = 'tls';
$mail->Port = 25;
*/
